# docker-compose.yml
version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"        # AMQP
      - "15672:15672"      # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-a:
    build: ./service-a
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  service-b:
    build: ./service-b
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  service-c:
    build: ./service-c
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  service-d:
    build: ./service-d
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  monitor:
    build: ./monitor
    depends_on:
      rabbitmq:
          condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  ws-server:
    build: ./ws-server
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  svelte-health:
    build: ./svelteHealth
    ports:
      - "5173:5173"      # Vite dev server default port
    depends_on:
      - ws-server
    environment:
      # Point the frontend at the WebSocket server
      VITE_WS_URL: ws://ws-server:4000/ws